---
name: Build VST

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select platform to build'
        required: true
        default: 'both'
        type: choice
        options:
          - both
          - macos
          - windows

concurrency:
  group: build-${{ inputs.platform }}
  cancel-in-progress: true

jobs:
  build:
    uses: eschirle/hise-plugin-workflows/.github/workflows/plugin_build.yaml@main
    with:
      platform: ${{ inputs.platform }}
      project-name: 'Dyes Tonguewuhh'
      use-ipp: false
    secrets: inherit
